version: '2'
services:
  redis:
    image: redis:3.2-alpine
    mem_limit: 64m
    memswap_limit: 64m

  docker-blah:
    image: amberovsky/docker-blah-development:0.2
    links:
      - redis
    ports:
      - ${HTTP_PORT}:80
      - ${SSH_PORT}:22
    volumes:
      - ${BRANCH}:/var/www/docker-blah/master
    depends_on:
      - redis
